### PR TITLE
Update from main to master

### PR DESCRIPTION
**Pull request by arthurmelton**
I realize I actually made a error with my other pr, this updates it from main to master.

### CODE REVIEW

**Comment by m1911star** [comment]
ah, in my opinion, i just want to keep up with the develop branch of main repo at least for now. So I will revert the previous commit and close this pr tomorrow, thanks.

**Comment by arthurmelton** [comment]
The master branch still gets updated very frequently.

**Comment by mitsuhatu** [comment]
The master branch will publish every two weeks.

**Comment by m1911star** [comment]
@mitsuhatu OK, i see~
@AMTitan  Can you commit the changes again which i just revert before~thx~

**Comment by arthurmelton** [comment]
@m1911star I think you are going to have to resolve the conflicts and pick my updates over the origin. I think that is what you are asking for atleast.

**Pull request merged**
